language: c

dist: xenial

os: linux

compiler: gcc

before_script:
    - python --version
    - python3 --version
    - ls
    - |
      cat <<-EOF > config.mak
      HARCH=linux-x86_64
      ARCHES +=
      USE_CXX11_default=NO
      INSTALL_DIR=/usr/local/cpsw
    - ls
    - cat config.mak

script: make && make test

after_success:
    # Create documentation that will be deployed:
    - echo "Generating documentation..."
    - mkdir html
    - echo "# Deployed documentation" >> index.md
    # - echo "<h1>Deployed documentation</h1>"   >> html/index.html
    # - echo "<a href=\"index.html\">page 1</a>" >> html/index.html
    # - echo "<h2>page 1...</h2>" >> html/page1.html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: html
  on:
    branch: master
