language: c

dist: xenial

os: linux

compiler: gcc

before_script:
    - python --version
    - python3 --version
    - ls
    - |
      cat <<-EOF > config.mak
      HARCH=linux-x86_64
      ARCHES +=
      USE_CXX11_default=NO
      INSTALL_DIR=/usr/local/cpsw
    - ls
    - cat config.mak

script: make && make test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
